package com.hotelvista.aiconcierge.model;

public enum BookingState {
    IDLE,
    ASKING_BOOKING_TYPE,
    COLLECTING_DAILY_DATE,
    COLLECTING_HOURLY_TIME,
    SEARCHING_AVAILABLE_ROOMS,
    SELECTING_ROOM,
    ASKING_SERVICES,
    SELECTING_SERVICES,
    COLLECTING_CUSTOMER_INFO,
    REVIEWING_BOOKING,
    CONFIRMING_BOOKING,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED
}
